<a href="https://colab.research.google.com/github/jesildabraganca0511/NLP/blob/main/notebooks/Day01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))

True
1
0
Tesla T4


In [3]:
!pip install -q transformers datasets evaluate accelerate sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.9 MB/s eta 0:00:00


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Tensor Initialization


Directly from data


In [5]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

From a NumPy array



In [6]:
import numpy as np

In [7]:
np_array=np.array(data)
x_numpy=torch.from_numpy(np_array)

In [8]:
print(x_numpy)

tensor([[1, 2],
        [3, 4]])


From another tensor:



In [9]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7139, 0.0458],
        [0.9800, 0.7073]]) 



With random or constant values:



In [15]:
shape=(3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [16]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6733, 0.1981, 0.5988, 0.1737],
        [0.1695, 0.1147, 0.1379, 0.6540],
        [0.4913, 0.2154, 0.3881, 0.3145]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


# TENSOR ATTRIBUTES

In [17]:
tensor= torch.rand(3,4)

In [18]:
print(f"Shape of the tensor: {tensor.shape}")
print(f"Datatype of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operations

In [26]:
device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)

tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Standard numpy-like indexing and slicing:



In [27]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
tensor.is_sparse

False

In [30]:
tensor1=tensor.to_sparse()

In [31]:
tensor1

tensor(indices=tensor([[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3],
                       [0, 2, 3, 0, 2, 3, 0, 2, 3, 0, 2, 3]]),
       values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
       size=(4, 4), nnz=12, layout=torch.sparse_coo)

In [38]:
t1=torch.concat([tensor,tensor],dim=1)

In [39]:
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [40]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [41]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


Tensor to NumPy array


In [42]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


NumPy array to Tensor


In [43]:
n = np.ones(5)
t = torch.from_numpy(n)

# AUTOGRAD

In [44]:
from torchvision.models import resnet18,ResNet18_Weights

In [45]:
model=resnet18(weights=ResNet18_Weights.DEFAULT)
data=torch.rand(1,3,64,64)
labels=torch.rand(1,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 183MB/s]


In [46]:
prediction = model(data) # forward pass

In [51]:
loss=(prediction-labels).sum()

In [52]:
loss.backward()

In [55]:
print(model.fc.weight.grad)

tensor([[0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595],
        [0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595],
        [0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595],
        ...,
        [0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595],
        [0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595],
        [0.9533, 1.0722, 0.8185,  ..., 0.7987, 0.9375, 1.0595]])


In [53]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-2,momentum=0.9)


In [56]:
optimizer.step()

if teh output for the backward pass is a vector we need to assisgn an external gradient vector conataining teh importance of the outputs

In [57]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [58]:
Q = 3*a**3 - b**2

In [59]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [60]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
