<a href="https://colab.research.google.com/github/jesildabraganca0511/NLP/blob/main/notebooks/Day01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))

True
1
0
Tesla T4


In [3]:
!pip install -q transformers datasets evaluate accelerate sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.9 MB/s eta 0:00:00


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Tensor Initialization


Directly from data


In [5]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

From a NumPy array



In [6]:
import numpy as np

In [7]:
np_array=np.array(data)
x_numpy=torch.from_numpy(np_array)

In [8]:
print(x_numpy)

tensor([[1, 2],
        [3, 4]])


From another tensor:



In [9]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7139, 0.0458],
        [0.9800, 0.7073]]) 



With random or constant values:



In [15]:
shape=(3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [16]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6733, 0.1981, 0.5988, 0.1737],
        [0.1695, 0.1147, 0.1379, 0.6540],
        [0.4913, 0.2154, 0.3881, 0.3145]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


# TENSOR ATTRIBUTES

In [17]:
tensor= torch.rand(3,4)

In [18]:
print(f"Shape of the tensor: {tensor.shape}")
print(f"Datatype of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operations

In [26]:
device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)

tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Standard numpy-like indexing and slicing:



In [27]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
